site_name: Playbook de Ética e Ingeniería
theme:
  name: material
  palette:
    scheme: preference
  features:
    - navigation.tabs # Crea pestañas superiores si el menú es muy largo
    - navigation.tabs.sticky
    - search.suggest

nav:
  - Inicio: index.md
  - Código de Ética (ACM/IEEE): codigo-etica.md
  - Clasificación de Incidentes: incidentes.md
  - Protocolos de Respuesta: protocolos.md
  - Seguridad (Stallings): seguridad.md
  - Inteligencia Artificial (Sommerville): inteligencia-artificial.md
  - Análisis de Riesgos: riesgos.md
  - Auditorías de Seguridad: auditorias.md
  - Buenas Prácticas (Pressman): buenas-practicas.md
